# HNSW Search Evaluation

Notebook ini mengevaluasi retrieval HNSW dari Qdrant terhadap `Ground truth - System.csv`. Karena response search di `src/search_engine.py` digroup berdasarkan agreement, evaluasi di sini melakukan flatten kembali ke level artikel: 10 agreement teratas x top 3 artikel per agreement = maksimum 30 artikel per query.

Grid evaluasi:
1. Collection hasil indexing: `m8/m16/m32` dan `ef_construct 100/200/400`
2. Parameter search: `hnsw_ef = 32, 64, 128, 256`
3. Limit pengembalian Qdrant: `10, 20, 30, 50, 100`

Catatan evaluasi: default notebook ini memakai **GT-pool filtering**, yaitu artikel hasil search yang tidak ada di ground truth dibuang sebelum menghitung NDCG@30. Ini sesuai kebutuhan pengujian terhadap artikel yang sudah diberi relevance. Jika ingin memberi penalti pada artikel yang tidak ada di GT, ubah `FILTER_TO_GT_POOL = False`.

In [40]:
from __future__ import annotations

import re
import sys
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

try:
    from IPython.display import display
except ImportError:
    display = print

# Path dibuat aman baik notebook dijalankan dari root repo maupun dari folder evaluation.
CWD = Path.cwd().resolve()
if (CWD / "Ground truth - System.csv").exists():
    EVAL_DIR = CWD
    PROJECT_ROOT = CWD.parent
else:
    PROJECT_ROOT = CWD
    EVAL_DIR = PROJECT_ROOT / "evaluation"

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))
if str(PROJECT_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))

import importlib
import src.config as config_module

# Reload dibutuhkan kalau config.py baru diedit tetapi kernel notebook belum direstart.
config_module = importlib.reload(config_module)
settings = config_module.settings

print("PROJECT_ROOT:", PROJECT_ROOT)
print("EVAL_DIR:", EVAL_DIR)
print("Config file:", config_module.__file__)

PROJECT_ROOT: /home/vinik/Github/vector-search-thesis
EVAL_DIR: /home/vinik/Github/vector-search-thesis/evaluation
Config file: /home/vinik/Github/vector-search-thesis/src/config.py

In [41]:
GT_PATH = EVAL_DIR / "Ground truth - System.csv"
OUTPUT_DIR = EVAL_DIR / "hnsw_eval_results"

COLLECTION_CONFIGS = [
    {
        "collection_id": "m8_ef100",
        "collection_name": settings.COLLECTION_HYBRID_M8_EF100,
        "m": 8,
        "ef_construct": 100,
    },
    {
        "collection_id": "m8_ef200",
        "collection_name": settings.COLLECTION_HYBRID_M8_EF200,
        "m": 8,
        "ef_construct": 200,
    },
    {
        "collection_id": "m8_ef400",
        "collection_name": settings.COLLECTION_HYBRID_M8_EF400,
        "m": 8,
        "ef_construct": 400,
    },
    {
        "collection_id": "m16_ef100",
        "collection_name": settings.COLLECTION_HYBRID_M16_EF100,
        "m": 16,
        "ef_construct": 100,
    },
    {
        "collection_id": "m16_ef200",
        "collection_name": settings.COLLECTION_HYBRID_M16_EF200,
        "m": 16,
        "ef_construct": 200,
    },
    {
        "collection_id": "m16_ef400",
        "collection_name": settings.COLLECTION_HYBRID_M16_EF400,
        "m": 16,
        "ef_construct": 400,
    },
    {
        "collection_id": "m32_ef100",
        "collection_name": settings.COLLECTION_HYBRID_M32_EF100,
        "m": 32,
        "ef_construct": 100,
    },
    {
        "collection_id": "m32_ef200",
        "collection_name": settings.COLLECTION_HYBRID_M32_EF200,
        "m": 32,
        "ef_construct": 200,
    },
    {
        "collection_id": "m32_ef400",
        "collection_name": settings.COLLECTION_HYBRID_M32_EF400,
        "m": 32,
        "ef_construct": 400,
    },
]

EF_VALUES = [16, 32, 64, 128, 256]
QDRANT_LIMIT_VALUES = list(range(10, 101, 10))
K = 30
AGREEMENT_LIMIT = 10
TOP_ARTICLES_PER_AGREEMENT = 3
TIMING_RUNS = 25
THRESHOLD = 0.0

# True = hanya hitung artikel yang ada di GT pool. False = artikel unjudged dihitung sebagai relevance 0.
FILTER_TO_GT_POOL = True

# Mode search per unit GT.
# negation=True memakai parser negation agar query seperti "without patents" menghasilkan excluded_terms.
# negation=False/NaN memakai HNSW murni tanpa parser negation.
SEARCH_MODE_BY_NEGATION = {
    True: "negation",
    False: "no_negation",
    None: "no_negation",
}

SEARCH_ENGINE_CONFIGS = {
    "no_negation": {
        "use_reranker": False,
        "use_llm": False,
        "use_finetuned": False,
    },
    "negation": {
        "use_reranker": False,
        "use_llm": False,
        "use_finetuned": True,
    },
}

collection_plan_df = pd.DataFrame(COLLECTION_CONFIGS)
print("Collections to evaluate:")
display(collection_plan_df)
print("Search hnsw_ef values:", EF_VALUES)
print("Qdrant return limits:", QDRANT_LIMIT_VALUES)

Collections to evaluate:

  collection_id        collection_name   m  ef_construct
0      m8_ef100   rtas_hybrid_m8_ef100   8           100
1      m8_ef200   rtas_hybrid_m8_ef200   8           200
2      m8_ef400   rtas_hybrid_m8_ef400   8           400
3     m16_ef100  rtas_hybrid_m16_ef100  16           100
4     m16_ef200  rtas_hybrid_m16_ef200  16           200
5     m16_ef400  rtas_hybrid_m16_ef400  16           400
6     m32_ef100  rtas_hybrid_m32_ef100  32           100
7     m32_ef200  rtas_hybrid_m32_ef200  32           200
8     m32_ef400  rtas_hybrid_m32_ef400  32           400

Search hnsw_ef values: [16, 32, 64, 128, 256]
Qdrant return limits: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

## Helper: Normalisasi, Ranking, dan NDCG

In [42]:
def parse_bool_like(value: Any) -> bool | None:
    if pd.isna(value):
        return None
    text = str(value).strip().lower()
    if text in {"true", "1", "yes", "y"}:
        return True
    if text in {"false", "0", "no", "n"}:
        return False
    return None


def parse_rank(rank_str: Any) -> tuple[int, int] | None:
    """Parse rank_qdrant as (agreement_rank, article_rank). Example: '1,2' = agreement top 1, article top 2."""
    if pd.isna(rank_str) or str(rank_str).strip() == "":
        return None
    try:
        parts = str(rank_str).replace('"', "").replace("'", "").strip().split(",")
        return int(float(parts[0])), int(float(parts[1]))
    except Exception:
        return None


def normalize_text(value: Any) -> str:
    if pd.isna(value):
        return ""
    text = str(value)
    text = text.replace("â", "'").replace("’", "'").replace(" ", " ")
    text = re.sub(r"\bartical\b", "article", text, flags=re.IGNORECASE)
    text = re.sub(r"\s+", " ", text).strip().casefold()
    return text


def normalize_rta_id(value: Any) -> str:
    if pd.isna(value) or str(value).strip() == "":
        return ""
    try:
        return str(int(float(value)))
    except Exception:
        return str(value).strip()


def make_rta_key(rta_id: Any, article_number: Any, article_title: Any) -> tuple[str, str, str, str] | None:
    rid = normalize_rta_id(rta_id)
    if not rid:
        return None
    return ("rta", rid, normalize_text(article_number), normalize_text(article_title))


def make_agreement_key(agreement_title: Any, article_number: Any, article_title: Any) -> tuple[str, str, str, str]:
    return (
        "agreement",
        normalize_text(agreement_title),
        normalize_text(article_number),
        normalize_text(article_title),
    )


def compute_dcg(scores: list[float]) -> float:
    return sum(rel / np.log2(idx + 2) for idx, rel in enumerate(scores))


def compute_ndcg(predicted_relevance: list[float], ideal_relevance: list[float], k: int = K) -> float:
    scores = list(predicted_relevance[:k])
    if len(scores) < k:
        scores.extend([0] * (k - len(scores)))
    ideal = sorted(list(ideal_relevance), reverse=True)[:k]
    idcg = compute_dcg(ideal)
    return compute_dcg(scores) / idcg if idcg > 0 else 0.0

## Load Ground Truth

Kolom `negation` dipakai untuk memisahkan Q02 menjadi dua unit evaluasi (`Q02_negation` dan `Q02_no_negation`) karena CSV berisi dua pool hasil untuk query yang sama.

In [43]:
def load_ground_truth(path: Path) -> pd.DataFrame:
    df = pd.read_csv(path)
    required_columns = {
        "query",
        "query_id",
        "rta_id",
        "agreement_title",
        "chapter_title",
        "article_number",
        "article_title",
        "article_text",
        "rank_qdrant",
        "relevance",
    }
    missing = required_columns - set(df.columns)
    if missing:
        raise ValueError(f"Missing GT columns: {sorted(missing)}")

    df = df.copy()
    df["relevance"] = pd.to_numeric(df["relevance"], errors="coerce").fillna(0).astype(float)
    df["negation_flag"] = df.get("negation", pd.Series([None] * len(df))).apply(parse_bool_like)

    def make_eval_id(row: pd.Series) -> str:
        if row["negation_flag"] is True:
            return f"{row['query_id']}_negation"
        if row["negation_flag"] is False:
            return f"{row['query_id']}_no_negation"
        return str(row["query_id"])

    df["eval_id"] = df.apply(make_eval_id, axis=1)
    rank_parts = df["rank_qdrant"].apply(parse_rank)
    df["parsed_rank_qdrant"] = rank_parts
    df["agreement_rank_qdrant"] = rank_parts.apply(lambda rank: rank[0] if rank else np.nan)
    df["article_rank_qdrant"] = rank_parts.apply(lambda rank: rank[1] if rank else np.nan)
    return df


gt_df = load_ground_truth(GT_PATH)
print("GT rows:", len(gt_df))
display(gt_df.groupby(["eval_id", "query_id", "query"], dropna=False).size().reset_index(name="gt_rows"))

GT rows: 108

,eval_id,query_id,query,gt_rows
0,Q01,Q01,customs clearance for perishable goods,29
1,Q02_negation,Q02,intellectual property protection without patents,25
2,Q02_no_negation,Q02,intellectual property protection without patents,26
3,Q03,Q03,labour standards in trade,28

In [44]:
def build_gt_lookup(df_unit: pd.DataFrame) -> dict[tuple[str, str, str, str], dict[str, Any]]:
    lookup = {}
    for idx, row in df_unit.iterrows():
        record = {
            "gt_index": idx,
            "relevance": float(row["relevance"]),
            "rta_id": row.get("rta_id"),
            "agreement_title": row.get("agreement_title"),
            "chapter_title": row.get("chapter_title"),
            "article_number": row.get("article_number"),
            "article_title": row.get("article_title"),
        }

        keys = [make_agreement_key(row.get("agreement_title"), row.get("article_number"), row.get("article_title"))]
        rta_key = make_rta_key(row.get("rta_id"), row.get("article_number"), row.get("article_title"))
        if rta_key is not None:
            keys.append(rta_key)

        for key in keys:
            # Jika ada duplikasi key dalam satu eval unit, pakai relevance tertinggi.
            if key not in lookup or record["relevance"] > lookup[key]["relevance"]:
                lookup[key] = record
    return lookup


def prediction_candidate_keys(item: dict[str, Any]) -> list[tuple[str, str, str, str]]:
    keys = [make_agreement_key(item.get("agreement"), item.get("article_number"), item.get("article_name"))]
    rta_key = make_rta_key(item.get("rta_id"), item.get("article_number"), item.get("article_name"))
    if rta_key is not None:
        keys.insert(0, rta_key)
    return keys


def find_prediction_in_gt(item: dict[str, Any], gt_lookup: dict[tuple[str, str, str, str], dict[str, Any]]):
    for key in prediction_candidate_keys(item):
        if key in gt_lookup:
            return key, gt_lookup[key]
    return None, None

## Baseline dari `rank_qdrant` di GT

Cell ini hanya membaca ranking yang sudah tersimpan di CSV, supaya hasil HNSW nanti punya pembanding awal.

`rank_qdrant` dibaca sebagai `(agreement_rank, article_rank)`. Contoh: `1,2` berarti agreement urutan 1 dan artikel urutan 2 dalam agreement tersebut.

In [45]:
def evaluate_gt_rank_column(gt: pd.DataFrame, k: int = K) -> pd.DataFrame:
    rows = []
    for eval_id, df_unit in gt.groupby("eval_id", sort=True):
        ranked = df_unit.dropna(subset=["parsed_rank_qdrant"]).copy()
        ranked = ranked.sort_values(["agreement_rank_qdrant", "article_rank_qdrant"])
        relevance_sequence = ranked["relevance"].tolist()[:k]
        ndcg = compute_ndcg(relevance_sequence, df_unit["relevance"].tolist(), k=k)
        rows.append(
            {
                "eval_id": eval_id,
                "query_id": df_unit["query_id"].iloc[0],
                "query": df_unit["query"].iloc[0],
                "gt_rows": len(df_unit),
                "ranked_rows": len(ranked),
                "rank_semantics": "agreement_rank,article_rank",
                f"ndcg_at_{k}": ndcg,
                "relevance_sequence": relevance_sequence,
            }
        )
    return pd.DataFrame(rows)


baseline_df = evaluate_gt_rank_column(gt_df, k=K)
display(baseline_df[["eval_id", "gt_rows", "ranked_rows", f"ndcg_at_{K}"]])
print("Mean baseline NDCG:", baseline_df[f"ndcg_at_{K}"].mean())

           eval_id  gt_rows  ranked_rows  ndcg_at_30
0              Q01       29           29    0.898623
1     Q02_negation       25           25    0.900094
2  Q02_no_negation       26           26    0.885123
3              Q03       28           28    0.923910

Mean baseline NDCG: 0.9019376156062544

## HNSW Search yang Mengikuti `SearchService`

Fungsi di bawah meniru bagian penting `SearchService.search`: query preprocessing, optional negation filtering, dedup chunk menjadi artikel, grouping per agreement, lalu flatten top 3 artikel dari 10 agreement teratas.

In [46]:
from qdrant_client import models
from qdrant_client.models import FieldCondition, Filter, MatchValue
import src.search_engine as search_engine_module

SearchService = search_engine_module.SearchService
localspelling = search_engine_module.localspelling


def prepare_query(engine: SearchService, user_query: str):
    excluded_terms = []
    llm_iso = None

    if engine.use_finetuned and engine.finetuned_parser:
        parsed = engine.finetuned_parser.parse(user_query)
        search_query = parsed["positive_query"]
        excluded_terms = parsed["excluded_terms"]
    elif engine.use_llm:
        parsed = engine.llm_query_parser(user_query)
        search_query = parsed["positive_query"]
        excluded_terms = parsed["excluded_terms"]
        llm_iso = parsed["iso_code"]
    else:
        search_query = user_query

    detected_iso = llm_iso or engine.detect_iso_from_query(search_query)
    qdrant_filter = None
    if detected_iso:
        qdrant_filter = Filter(
            must=[FieldCondition(key="iso", match=MatchValue(value=detected_iso))]
        )

    if not engine.use_finetuned:
        words = search_query.split()
        misspelled = engine.spell.unknown(words)
        corrected = []
        for word in words:
            if word in misspelled:
                correction = engine.spell.correction(word)
                corrected.append(correction if correction else word)
            else:
                corrected.append(word)
        search_query = " ".join(corrected)

    final_query = localspelling.convert_spelling(search_query, "us")
    excluded_terms = [localspelling.convert_spelling(term, "us") for term in excluded_terms]
    return final_query, excluded_terms, qdrant_filter


def build_result_from_hit(hit) -> dict[str, Any]:
    payload = hit.payload or {}
    article_text = payload.get("article_text") or "-"
    article_text_display = SearchService._resolve_article_text_display(
        payload.get("article_text_display"), article_text
    )
    score = float(hit.score)
    return {
        "id": hit.id,
        "rta_id": payload.get("rta_id"),
        "agreement": payload.get("Agreement") or "-",
        "chapter_name": payload.get("chapter_name") or "-",
        "article_id": payload.get("article_id"),
        "article_number": payload.get("article_number") or "-",
        "article_name": payload.get("article_name") or "-",
        "article_text": article_text,
        "article_text_display": article_text_display,
        "acronym": payload.get("acronym") or "-",
        "iso": payload.get("iso") or "-",
        "score": score,
        "confidence": f"{score:.4%}",
    }


def dedupe_hits_like_search_engine(hits) -> list[Any]:
    unique_hits = []
    seen_articles = set()
    for hit in hits:
        payload = hit.payload or {}
        unique_key = f"{payload.get('rta_id')}_{str(payload.get('article_name', '')).strip()}"
        if unique_key not in seen_articles:
            seen_articles.add(unique_key)
            unique_hits.append(hit)
    return unique_hits


def apply_negation_filter(results: list[dict[str, Any]], excluded_terms: list[str]) -> list[dict[str, Any]]:
    if not excluded_terms:
        return results
    filtered = []
    for item in results:
        text = item.get("article_text_display", "").lower()
        if not any(term.lower() in text for term in excluded_terms):
            filtered.append(item)
    return filtered


def group_by_agreement(results: list[dict[str, Any]], agreement_limit: int = AGREEMENT_LIMIT) -> list[dict[str, Any]]:
    grouped = {}
    for item in sorted(results, key=lambda x: x["score"], reverse=True):
        rta_id = item["rta_id"]
        if rta_id not in grouped:
            grouped[rta_id] = {
                "rta_id": rta_id,
                "agreement": item["agreement"],
                "acronym": item["acronym"],
                "iso": item["iso"],
                "best_score": item["score"],
                "best_confidence": item["confidence"],
                "articles": [],
            }
        grouped[rta_id]["articles"].append(
            {
                "id": item["id"],
                "chapter_name": item["chapter_name"],
                "article_id": item["article_id"],
                "article_number": item["article_number"],
                "article_name": item["article_name"],
                "article_text": item["article_text"],
                "article_text_display": item["article_text_display"],
                "score": item["score"],
                "confidence": item["confidence"],
            }
        )
    return sorted(grouped.values(), key=lambda x: x["best_score"], reverse=True)[:agreement_limit]


def flatten_grouped_results(grouped_results: list[dict[str, Any]], top_articles: int = TOP_ARTICLES_PER_AGREEMENT) -> list[dict[str, Any]]:
    flattened = []
    global_rank = 1
    for agreement_rank, group in enumerate(grouped_results, start=1):
        articles = sorted(group.get("articles", []), key=lambda x: x["score"], reverse=True)[:top_articles]
        for article_rank, article in enumerate(articles, start=1):
            flattened.append(
                {
                    "global_rank": global_rank,
                    "agreement_rank": agreement_rank,
                    "article_rank": article_rank,
                    "rta_id": group.get("rta_id"),
                    "agreement": group.get("agreement"),
                    **article,
                }
            )
            global_rank += 1
    return flattened


def hnsw_search_articles(
    engine: SearchService,
    query: str,
    hnsw_ef: int,
    collection_name: str,
    raw_limit: int,
    agreement_limit: int = AGREEMENT_LIMIT,
    top_articles: int = TOP_ARTICLES_PER_AGREEMENT,
    threshold: float = THRESHOLD,
) -> tuple[list[dict[str, Any]], float, str, int, int]:
    final_query, excluded_terms, qdrant_filter = prepare_query(engine, query)
    query_vector = engine.vector_model.encode(final_query).tolist()

    started = time.perf_counter()
    raw_hits = engine.client.query_points(
        collection_name=collection_name,
        query=query_vector,
        query_filter=qdrant_filter,
        limit=raw_limit,
        search_params=models.SearchParams(hnsw_ef=hnsw_ef),
        with_payload=True,
    ).points
    elapsed_ms = (time.perf_counter() - started) * 1000

    unique_hits = dedupe_hits_like_search_engine(raw_hits)
    results = [build_result_from_hit(hit) for hit in unique_hits]
    results = [item for item in results if item["score"] >= threshold]
    results = apply_negation_filter(results, excluded_terms)
    grouped = group_by_agreement(results, agreement_limit=agreement_limit)
    flattened = flatten_grouped_results(grouped, top_articles=top_articles)
    return flattened, elapsed_ms, final_query, len(raw_hits), len(unique_hits)

## Evaluasi HNSW terhadap Ground Truth

In [47]:
def relevance_from_predictions(
    predictions: list[dict[str, Any]],
    gt_lookup: dict[tuple[str, str, str, str], dict[str, Any]],
    filter_to_gt_pool: bool = FILTER_TO_GT_POOL,
    k: int = K,
) -> tuple[list[float], list[dict[str, Any]]]:
    relevance_sequence = []
    matched_rows = []
    seen_gt_keys = set()

    for prediction in predictions:
        gt_key, gt_record = find_prediction_in_gt(prediction, gt_lookup)

        if gt_record is None:
            if filter_to_gt_pool:
                continue
            relevance = 0.0
        else:
            if gt_key in seen_gt_keys:
                continue
            seen_gt_keys.add(gt_key)
            relevance = float(gt_record["relevance"])

        relevance_sequence.append(relevance)
        matched_rows.append(
            {
                "predicted_global_rank": prediction.get("global_rank"),
                "predicted_agreement_rank": prediction.get("agreement_rank"),
                "predicted_article_rank": prediction.get("article_rank"),
                "rta_id": prediction.get("rta_id"),
                "agreement": prediction.get("agreement"),
                "chapter_name": prediction.get("chapter_name"),
                "article_number": prediction.get("article_number"),
                "article_name": prediction.get("article_name"),
                "score": prediction.get("score"),
                "relevance": relevance,
                "matched_in_gt": gt_record is not None,
            }
        )

        if len(relevance_sequence) >= k:
            break

    return relevance_sequence, matched_rows


def get_unit_negation_flag(df_unit: pd.DataFrame) -> bool | None:
    flags = [flag for flag in df_unit["negation_flag"].dropna().unique().tolist()]
    if not flags:
        return None
    if len(flags) > 1:
        raise ValueError(f"One eval unit has mixed negation flags: {flags}")
    return bool(flags[0])


def get_search_mode(negation_flag: bool | None) -> str:
    return SEARCH_MODE_BY_NEGATION.get(negation_flag, "no_negation")


def get_search_engine_for_mode(
    search_mode: str,
    engine_cache: dict[str, SearchService],
) -> SearchService:
    if search_mode not in engine_cache:
        config = SEARCH_ENGINE_CONFIGS[search_mode]
        engine_cache[search_mode] = SearchService(**config)
    return engine_cache[search_mode]


def evaluate_hnsw_configs(
    gt: pd.DataFrame,
    collection_configs: list[dict[str, Any]] = COLLECTION_CONFIGS,
    ef_values: list[int] = EF_VALUES,
    qdrant_limit_values: list[int] = QDRANT_LIMIT_VALUES,
    k: int = K,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    summary_rows = []
    detail_rows = []
    search_cache = {}
    engine_cache = {}

    total_jobs = len(collection_configs) * len(ef_values) * len(qdrant_limit_values) * gt["eval_id"].nunique()
    done_jobs = 0

    for collection_config in collection_configs:
        collection_id = collection_config["collection_id"]
        collection_name = collection_config["collection_name"]
        print(f"Evaluating collection {collection_id} ({collection_name})")

        for hnsw_ef in ef_values:
            for qdrant_limit in qdrant_limit_values:
                for eval_id, df_unit in gt.groupby("eval_id", sort=True):
                    done_jobs += 1
                    query = df_unit["query"].iloc[0]
                    negation_flag = get_unit_negation_flag(df_unit)
                    search_mode = get_search_mode(negation_flag)
                    engine = get_search_engine_for_mode(search_mode, engine_cache)
                    cache_key = (collection_name, query, hnsw_ef, qdrant_limit, search_mode)

                    if cache_key not in search_cache:
                        predictions, elapsed_ms, final_query, raw_hit_count, unique_hit_count = hnsw_search_articles(
                            engine,
                            query,
                            hnsw_ef=hnsw_ef,
                            collection_name=collection_name,
                            raw_limit=qdrant_limit,
                        )
                        search_cache[cache_key] = (
                            predictions,
                            elapsed_ms,
                            final_query,
                            raw_hit_count,
                            unique_hit_count,
                        )
                    else:
                        predictions, elapsed_ms, final_query, raw_hit_count, unique_hit_count = search_cache[cache_key]

                    gt_lookup = build_gt_lookup(df_unit)
                    relevance_sequence, matched_rows = relevance_from_predictions(
                        predictions,
                        gt_lookup,
                        filter_to_gt_pool=FILTER_TO_GT_POOL,
                        k=k,
                    )
                    ndcg = compute_ndcg(relevance_sequence, df_unit["relevance"].tolist(), k=k)

                    summary_rows.append(
                        {
                            "collection_id": collection_id,
                            "collection_name": collection_name,
                            "m": collection_config["m"],
                            "ef_construct": collection_config["ef_construct"],
                            "hnsw_ef": hnsw_ef,
                            "qdrant_limit": qdrant_limit,
                            "eval_id": eval_id,
                            "query_id": df_unit["query_id"].iloc[0],
                            "query": query,
                            "negation_flag": negation_flag,
                            "search_mode": search_mode,
                            "engine_use_finetuned": engine.use_finetuned,
                            "engine_use_llm": engine.use_llm,
                            "engine_use_reranker": engine.use_reranker,
                            "final_query": final_query,
                            "gt_rows": len(df_unit),
                            "raw_hit_count": raw_hit_count,
                            "unique_hit_count": unique_hit_count,
                            "predicted_rows_before_gt_filter": len(predictions),
                            "predicted_rows_used": len(relevance_sequence),
                            "elapsed_ms_single_run": elapsed_ms,
                            f"ndcg_at_{k}": ndcg,
                            "relevance_sequence": relevance_sequence,
                        }
                    )

                    for rank_after_filter, row in enumerate(matched_rows, start=1):
                        detail_rows.append(
                            {
                                "collection_id": collection_id,
                                "collection_name": collection_name,
                                "m": collection_config["m"],
                                "ef_construct": collection_config["ef_construct"],
                                "hnsw_ef": hnsw_ef,
                                "qdrant_limit": qdrant_limit,
                                "eval_id": eval_id,
                                "negation_flag": negation_flag,
                                "search_mode": search_mode,
                                "rank_after_gt_filter": rank_after_filter,
                                **row,
                            }
                        )

                    if done_jobs % 20 == 0 or done_jobs == total_jobs:
                        print(f"  progress {done_jobs}/{total_jobs}")

    return pd.DataFrame(summary_rows), pd.DataFrame(detail_rows)

## Benchmark Latency HNSW

Latency benchmark dibuat terpisah dari evaluasi NDCG. Ini mengulang query Qdrant beberapa kali dengan `with_payload=False` agar fokus mengukur efek `hnsw_ef` pada search Qdrant.

In [48]:
def make_latency_specs(gt: pd.DataFrame) -> list[dict[str, Any]]:
    specs = []
    seen = set()
    for eval_id, df_unit in gt.groupby("eval_id", sort=True):
        query = df_unit["query"].iloc[0]
        negation_flag = get_unit_negation_flag(df_unit)
        search_mode = get_search_mode(negation_flag)
        key = (query, search_mode)
        if key in seen:
            continue
        seen.add(key)
        specs.append(
            {
                "eval_id": eval_id,
                "query": query,
                "negation_flag": negation_flag,
                "search_mode": search_mode,
            }
        )
    return specs


def benchmark_hnsw_latency(
    query_specs: list[dict[str, Any]],
    collection_configs: list[dict[str, Any]] = COLLECTION_CONFIGS,
    ef_values: list[int] = EF_VALUES,
    qdrant_limit_values: list[int] = QDRANT_LIMIT_VALUES,
    runs: int = TIMING_RUNS,
) -> pd.DataFrame:
    rows = []
    engine_cache = {}

    for collection_config in collection_configs:
        collection_id = collection_config["collection_id"]
        collection_name = collection_config["collection_name"]
        print(f"Benchmark latency collection {collection_id} ({collection_name})")

        for spec in query_specs:
            query = spec["query"]
            search_mode = spec["search_mode"]
            engine = get_search_engine_for_mode(search_mode, engine_cache)
            final_query, _, qdrant_filter = prepare_query(engine, query)
            query_vector = engine.vector_model.encode(final_query).tolist()

            # Warmup
            engine.client.query_points(
                collection_name=collection_name,
                query=query_vector,
                query_filter=qdrant_filter,
                limit=1,
                with_payload=False,
            )

            for hnsw_ef in ef_values:
                for qdrant_limit in qdrant_limit_values:
                    times = []
                    for _ in range(runs):
                        started = time.perf_counter()
                        engine.client.query_points(
                            collection_name=collection_name,
                            query=query_vector,
                            query_filter=qdrant_filter,
                            limit=qdrant_limit,
                            search_params=models.SearchParams(hnsw_ef=hnsw_ef),
                            with_payload=False,
                        )
                        times.append((time.perf_counter() - started) * 1000)

                    rows.append(
                        {
                            "collection_id": collection_id,
                            "collection_name": collection_name,
                            "m": collection_config["m"],
                            "ef_construct": collection_config["ef_construct"],
                            "eval_id": spec["eval_id"],
                            "query": query,
                            "negation_flag": spec["negation_flag"],
                            "search_mode": search_mode,
                            "engine_use_finetuned": engine.use_finetuned,
                            "engine_use_llm": engine.use_llm,
                            "final_query": final_query,
                            "hnsw_ef": hnsw_ef,
                            "qdrant_limit": qdrant_limit,
                            "runs": runs,
                            "avg_time_ms": float(np.mean(times)),
                            "min_time_ms": float(np.min(times)),
                            "max_time_ms": float(np.max(times)),
                            "std_time_ms": float(np.std(times)),
                        }
                    )
    return pd.DataFrame(rows)

## Jalankan Evaluasi

Jalankan cell ini saat Qdrant dan semua collection hasil indexing sudah aktif. Output lengkap disimpan ke `evaluation/hnsw_eval_results/`, termasuk ringkasan final untuk melihat konfigurasi terbaik secara cepat.

In [49]:
hnsw_summary_df, hnsw_detail_df = evaluate_hnsw_configs(
    gt_df,
    collection_configs=COLLECTION_CONFIGS,
    ef_values=EF_VALUES,
    qdrant_limit_values=QDRANT_LIMIT_VALUES,
    k=K,
)

summary_cols = [
    "collection_id",
    "m",
    "ef_construct",
    "hnsw_ef",
    "qdrant_limit",
    "eval_id",
    "negation_flag",
    "search_mode",
    "engine_use_finetuned",
    "gt_rows",
    "raw_hit_count",
    "unique_hit_count",
    "predicted_rows_before_gt_filter",
    "predicted_rows_used",
    "elapsed_ms_single_run",
    f"ndcg_at_{K}",
]
display(hnsw_summary_df[summary_cols].sort_values(["collection_id", "hnsw_ef", "qdrant_limit", "eval_id"]))

grid_preview_df = (
    hnsw_summary_df.groupby(["collection_id", "m", "ef_construct", "hnsw_ef", "qdrant_limit"])
    .agg(
        mean_ndcg=(f"ndcg_at_{K}", "mean"),
        min_ndcg=(f"ndcg_at_{K}", "min"),
        mean_elapsed_ms=("elapsed_ms_single_run", "mean"),
        mean_used_rows=("predicted_rows_used", "mean"),
    )
    .reset_index()
    .sort_values(["mean_ndcg", "mean_elapsed_ms"], ascending=[False, True])
)
display(grid_preview_df.head(20))

2026-05-29 01:14:34 - src.search_engine - INFO - [Init] Initializing model & database
2026-05-29 01:14:34 - httpx - INFO - HTTP Request: GET http://127.0.0.1:6333 "HTTP/1.1 200 OK"
2026-05-29 01:14:34 - sentence_transformers.SentenceTransformer - INFO - Use pytorch device_name: cuda:0
2026-05-29 01:14:34 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: all-mpnet-base-v2

Evaluating collection m8_ef100 (rtas_hybrid_m8_ef100)

2026-05-29 01:14:34 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:34 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-05-29 01:14:35 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:35 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-05-29 01:14:35 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:35 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-05-29 01:14:35 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:35 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:36 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 3197.17it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-29 01:14:38 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:38 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-05-29 01:14:38 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:38 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-05-29 01:14:38 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-05-29 01:14:38 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-05-29 01:14:39 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:39 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-05-29 01:14:39 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"
2026-05-29 01:14:40 - src.search_engine - INFO - [Init] Reranker: OFF (vector score only)
2026-05-29 01:14:40 - src.search_engine - INFO - [Init] Fine-tuned Parser: OFF
2026-05-29 01:14:40 - src.search_engine - INFO - [Init] LLM Query Parser: OFF
2026-05-29 01:14:40 - src.search_engine - INFO - [Init] System ready
Batches: 100%|██████████| 1/1 [00:00<00:00, 10.76it/s]
2026-05-29 01:14:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:41 - src.search_engine - INFO - [Init] Initializing model & database
2026-05-29 01:14:41 - httpx - INFO - HTTP Request: GET http://127.0.0.1:6333 "HTTP/1.1 200 OK"
2026-05-29 01:14:41 - sentence_transformers.SentenceTransformer - INFO - Use pytorch device_name: cuda:0
2026-05-29 01:14:41 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: all-mpnet-base-v2
2026-05-29 01:14:41 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:41 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-05-29 01:14:41 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:41 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-05-29 01:14:42 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:42 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-05-29 01:14:42 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:42 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
2026-05-29 01:14:42 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:42 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-05-29 01:14:43 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:43 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-05-29 01:14:43 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-05-29 01:14:43 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:43 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 7767.81it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-29 01:14:43 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:44 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-05-29 01:14:44 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:44 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-05-29 01:14:44 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-05-29 01:14:44 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-05-29 01:14:45 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:14:45 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-05-29 01:14:45 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"
2026-05-29 01:14:45 - src.search_engine - INFO - [Init] Reranker: OFF (vector score only)
2026-05-29 01:14:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Loading model from: /home/vinik/Github/vector-search-thesis/finetuning_negation/FLAN/negation_model_t5_v2
2026-05-29 01:14:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Device: cuda
Loading weights: 100%|██████████| 190/190 [00:00<00:00, 449.04it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
2026-05-29 01:14:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Model ready
2026-05-29 01:14:46 - src.search_engine - INFO - [Init] Fine-tuned Parser: ON
2026-05-29 01:14:46 - src.search_engine - INFO - [Init] LLM Query Parser: OFF
2026-05-29 01:14:46 - src.search_engine - INFO - [Init] System ready
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.58it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.18it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.30it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.87it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.11it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.38it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.65it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.44it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.55it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.64it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.49it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.55it/s]
2026-05-29 01:14:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.92it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.21it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.01it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.75it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.66it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.63it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 20/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 103.12it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.81it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.97it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.43it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.09it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.48it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.75it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.79it/s]
2026-05-29 01:14:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.05it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.02it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.09it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.84it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.34it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.85it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.20it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.00it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.32it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.16it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.10it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 40/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 128.29it/s]
2026-05-29 01:14:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.39it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.92it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.31it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.14it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.10it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.70it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.39it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.53it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.14it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.86it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.53it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.06it/s]
2026-05-29 01:14:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.91it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.58it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.23it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.49it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.44it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.01it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.09it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 60/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 128.39it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.78it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.69it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.88it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.94it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.02it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.13it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.17it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.50it/s]
2026-05-29 01:14:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.50it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.38it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.79it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.83it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.72it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.50it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.31it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.26it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.11it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.90it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.71it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 80/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 120.30it/s]
2026-05-29 01:14:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.77it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.88it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.79it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.54it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.32it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.36it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.84it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.00it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.14it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.36it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.53it/s]
2026-05-29 01:14:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.85it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.39it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.94it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.03it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.79it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.84it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 93.51it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 100/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 115.06it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.34it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.11it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.10it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.17it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 147.46it/s]
2026-05-29 01:14:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.04it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.02it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.04it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.15it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 93.20it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.47it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.98it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.05it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.37it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.57it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.93it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.60it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.77it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.93it/s]
2026-05-29 01:14:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 120/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 107.27it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.55it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.83it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.82it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.10it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.55it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.92it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.99it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.08it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.88it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.13it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.10it/s]
2026-05-29 01:14:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.50it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.10it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.00it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.40it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.58it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.13it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.49it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 140/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 113.75it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.11it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.19it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.81it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.10it/s]
2026-05-29 01:14:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.95it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.13it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.14it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.01it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.16it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.05it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.29it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.10it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.70it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.80it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.12it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.12it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 78.80it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.53it/s]
2026-05-29 01:14:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 160/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 108.08it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.29it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.54it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.48it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.00it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.70it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.71it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.75it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:14:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.78it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.43it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.67it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.31it/s]
2026-05-29 01:14:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.81it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.63it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.52it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.69it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.96it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.18it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 180/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 111.37it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.54it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.34it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.46it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.17it/s]
2026-05-29 01:15:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.20it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.57it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.90it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.62it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.04it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.42it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.59it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.47it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.81it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 91.20it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.73it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.29it/s]
2026-05-29 01:15:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.27it/s]
2026-05-29 01:15:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
2026-05-29 01:15:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.03it/s]
2026-05-29 01:15:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

  progress 200/1800
Evaluating collection m8_ef200 (rtas_hybrid_m8_ef200)

Batches: 100%|██████████| 1/1 [00:00<00:00, 125.09it/s]
2026-05-29 01:15:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.61it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.48it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.41it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.47it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.29it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.10it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.76it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.96it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.25it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.65it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.72it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.72it/s]
2026-05-29 01:15:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.02it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.71it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.23it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.47it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.65it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.81it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.35it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 220/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 107.69it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.24it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.24it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.07it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.90it/s]
2026-05-29 01:15:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.94it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.68it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.42it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.55it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.64it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.01it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.07it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.15it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.90it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.84it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.84it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 90.35it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.69it/s]
2026-05-29 01:15:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 80.43it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.46it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 240/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 122.71it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.03it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.93it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.91it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.52it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.45it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.71it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.46it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.63it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.24it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.86it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.15it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.08it/s]
2026-05-29 01:15:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.38it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.84it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.34it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.75it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.70it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.45it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.21it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 260/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 100.80it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.54it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.83it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.01it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.48it/s]
2026-05-29 01:15:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.97it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.69it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.20it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.73it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.31it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.22it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.29it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.45it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.16it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.97it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.51it/s]
2026-05-29 01:15:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.62it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.62it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.85it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 280/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.59it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.87it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.82it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.94it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.46it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.55it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 88.64it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.94it/s]
2026-05-29 01:15:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.53it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.97it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.40it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.55it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.08it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.28it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.95it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.02it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.08it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.23it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.65it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 300/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 126.57it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.92it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.54it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.69it/s]
2026-05-29 01:15:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.03it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.69it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.83it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.50it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 146.61it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.73it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.80it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.15it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.88it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.59it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.31it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.14it/s]
2026-05-29 01:15:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.87it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.08it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.55it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 320/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 93.21it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.92it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.66it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.95it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.90it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.36it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.25it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 95.82it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.20it/s]
2026-05-29 01:15:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.73it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.88it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.09it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.78it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 147.62it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.22it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.85it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.66it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.03it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.80it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.47it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 340/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 114.81it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.33it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.88it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.28it/s]
2026-05-29 01:15:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.16it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.32it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.66it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.03it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.57it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.74it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.60it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.45it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.47it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.37it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.03it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.11it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.77it/s]
2026-05-29 01:15:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.65it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.82it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 360/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 128.33it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.61it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.50it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.53it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.71it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.27it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.06it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.24it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.04it/s]
2026-05-29 01:15:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.12it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.21it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.74it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.58it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.85it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.40it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.29it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.44it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.63it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.88it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.70it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 380/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 119.51it/s]
2026-05-29 01:15:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.02it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.90it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.77it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.95it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.45it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.38it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.84it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.93it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.77it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.45it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.35it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.59it/s]
2026-05-29 01:15:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.07it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.47it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.95it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.07it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.77it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.87it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.57it/s]
2026-05-29 01:15:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

  progress 400/1800
Evaluating collection m8_ef400 (rtas_hybrid_m8_ef400)

Batches: 100%|██████████| 1/1 [00:00<00:00, 117.73it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.60it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.06it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.90it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.13it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.76it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.22it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.05it/s]
2026-05-29 01:15:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.92it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.44it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.62it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.84it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.50it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.19it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.54it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.59it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.68it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.37it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.95it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 420/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
2026-05-29 01:15:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.12it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.31it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.60it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.80it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.08it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.58it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.07it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.72it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.89it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.80it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.56it/s]
2026-05-29 01:15:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.30it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.22it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.92it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.06it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.61it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.39it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.93it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 440/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 98.73it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.58it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.06it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.08it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.56it/s]
2026-05-29 01:15:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.67it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.15it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.43it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.55it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.70it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.45it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.43it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.19it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.17it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.99it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.56it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.35it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.49it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.74it/s]
2026-05-29 01:15:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.47it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 460/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 116.81it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.41it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.04it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.16it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 93.31it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.41it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.89it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.43it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.03it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.48it/s]
2026-05-29 01:15:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.76it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.04it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.62it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.37it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.45it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.30it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.73it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.73it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.27it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 480/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 131.94it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.42it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.09it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.36it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.11it/s]
2026-05-29 01:15:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 143.38it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.85it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.14it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.11it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.70it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.05it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.79it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.99it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.68it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.80it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.12it/s]
2026-05-29 01:15:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.96it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.95it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.48it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 500/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 111.28it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.59it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.87it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.77it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.32it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.31it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.66it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.80it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.19it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 143.54it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.15it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.62it/s]
2026-05-29 01:15:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.15it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.93it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.70it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.70it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.87it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.93it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.64it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 520/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 114.17it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.99it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.61it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.58it/s]
2026-05-29 01:15:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.14it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.23it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.63it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.97it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.54it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.67it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.39it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.43it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.27it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.58it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.80it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.97it/s]
2026-05-29 01:15:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.63it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.37it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.71it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 540/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 129.66it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.81it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.36it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.89it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.12it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.86it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.55it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.21it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.14it/s]
2026-05-29 01:15:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.46it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.75it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.10it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.98it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.64it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.64it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 89.33it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.94it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.43it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.93it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 560/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 124.10it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.01it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.44it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.05it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.15it/s]
2026-05-29 01:15:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.58it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.28it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.44it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.61it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.75it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.76it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.53it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.30it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.88it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.58it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.95it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.79it/s]
2026-05-29 01:15:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.83it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.96it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.52it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 580/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 118.83it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.38it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.22it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.70it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.46it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.40it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.13it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.87it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 95.46it/s]
2026-05-29 01:15:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.08it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.54it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.98it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.51it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.46it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.02it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.16it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.78it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.46it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.49it/s]
2026-05-29 01:15:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

  progress 600/1800
Evaluating collection m16_ef100 (rtas_hybrid_m16_ef100)

Batches: 100%|██████████| 1/1 [00:00<00:00, 108.31it/s]
2026-05-29 01:15:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.40it/s]
2026-05-29 01:15:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.84it/s]
2026-05-29 01:15:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.62it/s]
2026-05-29 01:15:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.45it/s]
2026-05-29 01:15:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.30it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.79it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.03it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.27it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.36it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.39it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.21it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.81it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.85it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.43it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.14it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.22it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.66it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
2026-05-29 01:15:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 620/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 129.19it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.59it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.98it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.46it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.33it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.55it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.18it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.98it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.94it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.99it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 82.60it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.62it/s]
2026-05-29 01:15:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.99it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.89it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.22it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.93it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.08it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.36it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.54it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 640/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 127.68it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.76it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.35it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.12it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.54it/s]
2026-05-29 01:15:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.83it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.61it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.03it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.48it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.10it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.42it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.05it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.09it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.95it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.10it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.90it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.47it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.42it/s]
2026-05-29 01:15:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.50it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.45it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 660/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 120.22it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.52it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.44it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.27it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.92it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.81it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.30it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.94it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.55it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.21it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.04it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.81it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.75it/s]
2026-05-29 01:15:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 92.84it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.25it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.12it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.43it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.55it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.87it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.07it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 680/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 115.05it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.25it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.77it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.27it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.81it/s]
2026-05-29 01:15:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.14it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.31it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.46it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.06it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.79it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.70it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.85it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.70it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.90it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.93it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.83it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.60it/s]
2026-05-29 01:15:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.38it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 90.20it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 91.48it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 700/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 90.39it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.21it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.83it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.39it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.06it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.39it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.77it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.86it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.26it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.89it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.71it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.14it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.15it/s]
2026-05-29 01:15:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.18it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.63it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.13it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.44it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.26it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.72it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.76it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 720/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 123.25it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.43it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.59it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.32it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.86it/s]
2026-05-29 01:15:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.27it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.85it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.08it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.46it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.61it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.76it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.97it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.81it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.82it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.00it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.52it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 146.80it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.14it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.99it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 740/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 132.68it/s]
2026-05-29 01:15:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.65it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.30it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.68it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.22it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.13it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.44it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.72it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.96it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.42it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.25it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.17it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
2026-05-29 01:15:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.95it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.76it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.64it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.81it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.06it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.41it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.40it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 760/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 106.99it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.82it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.23it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.02it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
2026-05-29 01:15:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.92it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.02it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.86it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.58it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.10it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.34it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.38it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.99it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.08it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 82.51it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 69.37it/s]
2026-05-29 01:15:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.82it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.07it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 780/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 111.48it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.76it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.84it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.23it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.57it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.46it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.07it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.21it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.03it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.54it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.41it/s]
2026-05-29 01:15:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.12it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.66it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.73it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.47it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.55it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.36it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.12it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.36it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.36it/s]
2026-05-29 01:15:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

  progress 800/1800
Evaluating collection m16_ef200 (rtas_hybrid_m16_ef200)

Batches: 100%|██████████| 1/1 [00:00<00:00, 129.63it/s]
2026-05-29 01:15:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.63it/s]
2026-05-29 01:15:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.11it/s]
2026-05-29 01:15:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.94it/s]
2026-05-29 01:15:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.06it/s]
2026-05-29 01:15:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.78it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.43it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.28it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.14it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.79it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.89it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.14it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.21it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.41it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.32it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.34it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.34it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 820/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 125.63it/s]
2026-05-29 01:15:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.40it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.77it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.53it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.82it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.61it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.96it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.44it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.25it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.51it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.49it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.27it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.75it/s]
2026-05-29 01:15:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.35it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.42it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.17it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.55it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.56it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.44it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.46it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 840/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 119.64it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.87it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.82it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.39it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.18it/s]
2026-05-29 01:15:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.46it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.21it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.03it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.64it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.65it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.27it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.44it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.31it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.39it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.78it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.50it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.08it/s]
2026-05-29 01:15:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.01it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.88it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.83it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 860/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 118.06it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.04it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.51it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.33it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.23it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.30it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.28it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.91it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.79it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.29it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.72it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.98it/s]
2026-05-29 01:15:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.87it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.56it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.18it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.61it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.94it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.33it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 880/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 139.71it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.87it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.90it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.48it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.03it/s]
2026-05-29 01:15:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.48it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.05it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.26it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.50it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.55it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.48it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.07it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.50it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.27it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.58it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.56it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.81it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.71it/s]
2026-05-29 01:15:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.50it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.03it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 900/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 121.58it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.19it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.43it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.21it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.06it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.74it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.91it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.47it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.85it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:15:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.36it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.98it/s]
2026-05-29 01:15:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.10it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.97it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.35it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.70it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.20it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.94it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.60it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.40it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 920/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 117.93it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.70it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.08it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.28it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.84it/s]
2026-05-29 01:16:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.02it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.50it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.04it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.54it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.39it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.52it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.42it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.64it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.65it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.10it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.09it/s]
2026-05-29 01:16:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.88it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.44it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.93it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 940/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.76it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.09it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.82it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.39it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.25it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.66it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.80it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.63it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.82it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.08it/s]
2026-05-29 01:16:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.51it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.22it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.03it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.41it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.09it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.97it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.89it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.38it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.61it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 960/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 133.01it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.00it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.59it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.33it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.04it/s]
2026-05-29 01:16:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.17it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.81it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.75it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.24it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.47it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.16it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.22it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.50it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.17it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.74it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.37it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.55it/s]
2026-05-29 01:16:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.60it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.30it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.11it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 980/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 102.37it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.85it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.47it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.76it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.61it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.02it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.16it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.18it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.07it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.07it/s]
2026-05-29 01:16:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.00it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.99it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.39it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.50it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.05it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.76it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.47it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.64it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.61it/s]
2026-05-29 01:16:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

  progress 1000/1800
Evaluating collection m16_ef400 (rtas_hybrid_m16_ef400)

Batches: 100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
2026-05-29 01:16:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.52it/s]
2026-05-29 01:16:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.94it/s]
2026-05-29 01:16:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.83it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.89it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.55it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.29it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.72it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.89it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.41it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.96it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.02it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.80it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.76it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.14it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 90.01it/s]
2026-05-29 01:16:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.10it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.21it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.10it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1020/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 109.60it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.02it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.62it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.78it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.88it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.32it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.58it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.04it/s]
2026-05-29 01:16:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.55it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.70it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.07it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.42it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.36it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.25it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.67it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.32it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.25it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.13it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.67it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1040/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 111.28it/s]
2026-05-29 01:16:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.76it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.74it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.00it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 89.01it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.40it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.65it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.18it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.07it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:11 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.82it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.32it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.70it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.86it/s]
2026-05-29 01:16:11 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.89it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.64it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.79it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.47it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.96it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.71it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.05it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1060/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 132.45it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.46it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.17it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.61it/s]
2026-05-29 01:16:12 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:12 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.57it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.49it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.42it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.02it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.75it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.96it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.87it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.30it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.18it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.86it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.72it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:13 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.92it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.25it/s]
2026-05-29 01:16:13 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.93it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1080/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 123.77it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.53it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.36it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.30it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.22it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 149.19it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.48it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.45it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 82.81it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:14 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.52it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.52it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.89it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.20it/s]
2026-05-29 01:16:14 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.72it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.16it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.50it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.22it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.83it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.64it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.16it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1100/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 113.72it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:15 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.43it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.95it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.05it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.03it/s]
2026-05-29 01:16:15 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.33it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.35it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.99it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.36it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.05it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.51it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.88it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.77it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.16it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.67it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.43it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.26it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:16 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
2026-05-29 01:16:16 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.97it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 92.11it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1120/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 146.21it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.50it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.66it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.12it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.06it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.03it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.91it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.13it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:17 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.05it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.81it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.07it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.96it/s]
2026-05-29 01:16:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.46it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.40it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.06it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.95it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.83it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.99it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1140/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 97.65it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:18 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.53it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.07it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.34it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.85it/s]
2026-05-29 01:16:18 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.99it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.32it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.16it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.77it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.79it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.47it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.93it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.92it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:19 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.90it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.88it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.10it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 91.61it/s]
2026-05-29 01:16:19 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.30it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.12it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1160/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 112.32it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.49it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.07it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.18it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.78it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.28it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.51it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.27it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:20 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.08it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.61it/s]
2026-05-29 01:16:20 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.96it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.34it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.12it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.28it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.82it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.48it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.09it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.83it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.63it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1180/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 124.59it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:21 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.24it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.21it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 91.30it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.30it/s]
2026-05-29 01:16:21 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.67it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.96it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.47it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.28it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.84it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.41it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.36it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:22 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.54it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.64it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.74it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.44it/s]
2026-05-29 01:16:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.09it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.37it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.21it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

  progress 1200/1800
Evaluating collection m32_ef100 (rtas_hybrid_m32_ef100)

Batches: 100%|██████████| 1/1 [00:00<00:00, 108.10it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:23 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.07it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.58it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.90it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.31it/s]
2026-05-29 01:16:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.70it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.41it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.47it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.09it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.36it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.94it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.26it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.33it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:24 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.37it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.06it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.96it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.24it/s]
2026-05-29 01:16:24 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.04it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.16it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.82it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1220/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 115.17it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.51it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.94it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.47it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 82.88it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:25 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.48it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.47it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.44it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.82it/s]
2026-05-29 01:16:25 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.85it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.49it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.20it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.22it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.00it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.01it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.21it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.58it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.07it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.17it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1240/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 113.14it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:26 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.17it/s]
2026-05-29 01:16:26 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.42it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.92it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.36it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.16it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.22it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.99it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.95it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.16it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.70it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.00it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:27 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.46it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.29it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.41it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.01it/s]
2026-05-29 01:16:27 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.84it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.62it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.13it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1260/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 115.18it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.91it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.98it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.17it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.44it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:28 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.67it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.01it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.51it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.90it/s]
2026-05-29 01:16:28 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.57it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.32it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.03it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.54it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.62it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.96it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.60it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.85it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.45it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.49it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.88it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1280/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 107.71it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:29 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.40it/s]
2026-05-29 01:16:29 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.16it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.88it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.83it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.06it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.51it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.95it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.26it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.18it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 86.19it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.17it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.28it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:30 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.14it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.74it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.64it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.75it/s]
2026-05-29 01:16:30 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.21it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.34it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.26it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1300/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 114.55it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.71it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 89.41it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 93.40it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.52it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:31 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.30it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.94it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.13it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.38it/s]
2026-05-29 01:16:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.29it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.04it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.57it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.41it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.28it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.25it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.74it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.25it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:32 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.08it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.41it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.55it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1320/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 119.25it/s]
2026-05-29 01:16:32 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.27it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.41it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.48it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.30it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.36it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.82it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.65it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.61it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.61it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.89it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.14it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.92it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:33 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.45it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.61it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.54it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.15it/s]
2026-05-29 01:16:33 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.39it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.55it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.22it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1340/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 120.49it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.67it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.13it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.53it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.97it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:34 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.93it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.95it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.05it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.28it/s]
2026-05-29 01:16:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.45it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.34it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.10it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.10it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.71it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.05it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.04it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.71it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:35 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.58it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.00it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.81it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1360/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 110.77it/s]
2026-05-29 01:16:35 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.19it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.91it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.74it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.65it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 148.88it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.16it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.42it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.67it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.75it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.35it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.22it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.48it/s]
2026-05-29 01:16:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:36 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.56it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.57it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.44it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.04it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.93it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.48it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.85it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1380/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 128.89it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.00it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.94it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.10it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.66it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:37 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.92it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.72it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.20it/s]
2026-05-29 01:16:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.62it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.17it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.54it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 91.64it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.18it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.32it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.38it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.48it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:38 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.94it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.50it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.00it/s]
2026-05-29 01:16:38 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

  progress 1400/1800
Evaluating collection m32_ef200 (rtas_hybrid_m32_ef200)

Batches: 100%|██████████| 1/1 [00:00<00:00, 108.30it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.89it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.33it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.32it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.42it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:39 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 145.93it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.12it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.06it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.81it/s]
2026-05-29 01:16:39 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.93it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.42it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.78it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.55it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.64it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.88it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.81it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.96it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:40 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.70it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.59it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.46it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1420/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 111.04it/s]
2026-05-29 01:16:40 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.93it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.81it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.11it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.95it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.94it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.74it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.20it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.81it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.67it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.32it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.07it/s]
2026-05-29 01:16:41 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:41 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.25it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.70it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.96it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.52it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.01it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.56it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.90it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1440/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 115.37it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.76it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.33it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.10it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.75it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:42 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.31it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.20it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.65it/s]
2026-05-29 01:16:42 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.54it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.20it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.17it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.61it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.46it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.41it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.31it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.93it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:43 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.09it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.82it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.50it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1460/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 103.28it/s]
2026-05-29 01:16:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.98it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.63it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.45it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.67it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.64it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.72it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.08it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:44 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.67it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.65it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.07it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.77it/s]
2026-05-29 01:16:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.61it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.05it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.03it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.51it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.37it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.12it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1480/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 110.70it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.97it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.37it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.34it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.10it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:45 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.99it/s]
2026-05-29 01:16:45 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.39it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.09it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.93it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.89it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.70it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.82it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.42it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.09it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.85it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:46 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 144.72it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.54it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.05it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1500/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 113.49it/s]
2026-05-29 01:16:46 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.31it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.56it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.33it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.89it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.45it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.12it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.09it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.23it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:47 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.73it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.84it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.89it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.53it/s]
2026-05-29 01:16:47 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.68it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.67it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.39it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.42it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.67it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.96it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.47it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1520/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 97.42it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.31it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.10it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.95it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.26it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:48 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.72it/s]
2026-05-29 01:16:48 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 85.46it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.29it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.32it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 92.88it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.54it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.94it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.46it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.20it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.90it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 84.80it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:49 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.17it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.05it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.66it/s]
2026-05-29 01:16:49 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1540/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 134.78it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.53it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.92it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.00it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.08it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.80it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.42it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.93it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.27it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:50 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.00it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.21it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.30it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.90it/s]
2026-05-29 01:16:50 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.73it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.78it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.15it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.82it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.02it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.19it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.82it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1560/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 108.83it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:51 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.53it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.15it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.98it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.45it/s]
2026-05-29 01:16:51 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.77it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.81it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.28it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.35it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.77it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 94.60it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.46it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.72it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:52 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 143.87it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.54it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.84it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.32it/s]
2026-05-29 01:16:52 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.13it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.73it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.52it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1580/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 109.84it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.77it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.90it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.99it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.32it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.40it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.74it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.16it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.33it/s]
2026-05-29 01:16:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:53 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 146.17it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.16it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.88it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.24it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.11it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.33it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.74it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.85it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.20it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.90it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

  progress 1600/1800
Evaluating collection m32_ef400 (rtas_hybrid_m32_ef400)

Batches: 100%|██████████| 1/1 [00:00<00:00, 123.43it/s]
2026-05-29 01:16:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:54 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.27it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.68it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.40it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.79it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.60it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.62it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.03it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.64it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 137.85it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.56it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.21it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.04it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:55 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 143.16it/s]
2026-05-29 01:16:55 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.68it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.45it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.65it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.92it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.79it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 100.08it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1620/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 106.24it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.04it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.48it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.44it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.76it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:56 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 135.79it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.04it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.70it/s]
2026-05-29 01:16:56 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.60it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.61it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.60it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.06it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 93.43it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.41it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.61it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.35it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.86it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:57 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.84it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.56it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.34it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1640/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 114.64it/s]
2026-05-29 01:16:57 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.61it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.81it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.92it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.36it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.96it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.74it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.99it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:58 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.28it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.19it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.00it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.97it/s]
2026-05-29 01:16:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.95it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.15it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.79it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 98.13it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.58it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.52it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.03it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1660/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 91.08it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.67it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.37it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 102.48it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.48it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:16:59 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.40it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.47it/s]
2026-05-29 01:16:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.74it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.64it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.50it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.24it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.51it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.31it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.92it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.28it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.93it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.56it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:00 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 134.13it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.61it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.62it/s]
2026-05-29 01:17:00 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1680/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 94.32it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.72it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.52it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.57it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.15it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.54it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 107.66it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.68it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.18it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:01 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.80it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.91it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.05it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 126.56it/s]
2026-05-29 01:17:01 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.72it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.81it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.95it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.80it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.49it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.94it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1700/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 135.93it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.19it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.51it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.19it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 105.68it/s]
2026-05-29 01:17:02 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:02 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.86it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.67it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.80it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.72it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.83it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.76it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.74it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.45it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.83it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.64it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.82it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:03 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.57it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 104.82it/s]
2026-05-29 01:17:03 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1720/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 125.24it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 140.94it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.51it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.31it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.05it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.53it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.20it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.92it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:04 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.11it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 112.20it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.32it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.03it/s]
2026-05-29 01:17:04 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 139.90it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.05it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.93it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.40it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.54it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.80it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.20it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1740/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 126.48it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:05 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 133.25it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.39it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.59it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 90.34it/s]
2026-05-29 01:17:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 138.56it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 111.57it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.47it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.38it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 141.24it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.12it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.34it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.21it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:06 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.21it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 109.89it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.66it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 110.87it/s]
2026-05-29 01:17:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.80it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 103.85it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 99.52it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1760/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 113.19it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 122.62it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.85it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.34it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.14it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.45it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.25it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 120.39it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.43it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:07 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 127.52it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.23it/s]
2026-05-29 01:17:07 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 121.71it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 113.17it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 128.31it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 117.74it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.25it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 114.12it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 123.26it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 119.24it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.14it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1780/1800

Batches: 100%|██████████| 1/1 [00:00<00:00, 117.99it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:08 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.94it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 131.16it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 129.38it/s]
2026-05-29 01:17:08 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 142.29it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.55it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.69it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.66it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.25it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 108.70it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 115.94it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 101.43it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:09 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 130.94it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 96.44it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 106.77it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 97.15it/s]
2026-05-29 01:17:09 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Query   : 'intellectual property protection without patents'
2026-05-29 01:17:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Raw out : 'positive: intellectual property protection | excluded: patents | country: none'
2026-05-29 01:17:10 - finetuning_negation.FLAN.inference - INFO - [NegationParser] Parsed  : {'positive_query': 'intellectual property protection', 'excluded_terms': ['patents'], 'iso_code': None, 'confidence': 1.0, 'raw': 'positive: intellectual property protection | excluded: patents | country: none'}
Batches: 100%|██████████| 1/1 [00:00<00:00, 136.52it/s]
2026-05-29 01:17:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 132.12it/s]
2026-05-29 01:17:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
Batches: 100%|██████████| 1/1 [00:00<00:00, 116.98it/s]
2026-05-29 01:17:10 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

  progress 1800/1800

,collection_id,m,ef_construct,hnsw_ef,qdrant_limit,eval_id,negation_flag,search_mode,engine_use_finetuned,gt_rows,raw_hit_count,unique_hit_count,predicted_rows_before_gt_filter,predicted_rows_used,elapsed_ms_single_run,ndcg_at_30
600,m16_ef100,16,100,16,10,Q01,None,no_negation,False,29,10,10,10,9,737.257931,0.654943
601,m16_ef100,16,100,16,10,Q02_negation,True,negation,True,25,10,10,3,2,24.926887,0.196040
602,m16_ef100,16,100,16,10,Q02_no_negation,False,no_negation,False,26,10,10,3,2,6.103338,0.238238
603,m16_ef100,16,100,16,10,Q03,None,no_negation,False,28,10,10,9,8,23.932580,0.454744
604,m16_ef100,16,100,16,20,Q01,None,no_negation,False,29,20,20,10,9,10.945953,0.654943
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,m8_ef400,8,400,256,90,Q03,None,no_negation,False,28,90,85,22,19,12.774104,0.836720
596,m8_ef400,8,400,256,100,Q01,None,no_negation,False,29,100,97,17,16,13.388570,0.779092
597,m8_ef400,8,400,256,100,Q02_negation,True,negation,True,25,100,100,16,16,10.703452,0.702977
598,m8_ef400,8,400,256,100,Q02_no_negation,False,no_negation,False,26,100,100,17,15,11.366992,0.718324
599,m8_ef400,8,400,256,100,Q03,None,no_negation,False,28,100,94,22,19,12.740039,0.836720

,collection_id,m,ef_construct,hnsw_ef,qdrant_limit,mean_ndcg,min_ndcg,mean_elapsed_ms,mean_used_rows
449,m8_ef400,8,400,256,100,0.759278,0.702977,12.049763,16.50
89,m16_ef200,16,200,128,100,0.754368,0.657336,10.752022,16.25
129,m16_ef400,16,400,64,100,0.752622,0.676352,13.113561,16.25
139,m16_ef400,16,400,128,100,0.751237,0.644809,11.878017,16.25
439,m8_ef400,8,400,128,100,0.751129,0.670381,11.261474,16.25
199,m32_ef100,32,100,256,100,0.750912,0.669514,12.001590,16.25
79,m16_ef200,16,200,64,100,0.749935,0.691368,9.965631,16.25
249,m32_ef200,32,200,256,100,0.748789,0.661020,13.022440,16.00
149,m16_ef400,16,400,256,100,0.745883,0.676352,12.970953,16.25
279,m32_ef400,32,400,64,100,0.745109,0.646302,11.046789,16.25
99,m16_ef200,16,200,256,100,0.744123,0.625917,14.427926,16.00
419,m8_ef400,8,400,32,100,0.742050,0.661020,13.307236,16.00
409,m8_ef400,8,400,16,100,0.742050,0.661020,13.358433,16.00
69,m16_ef200,16,200,32,100,0.738069,0.600919,10.160149,16.00
59,m16_ef200,16,200,16,100,0.738069,0.600919,13.373284,16.00
148,m16_ef400,16,400,256,90,0.737270,0.612010,12.037596,15.75
429,m8_ef400,8,400,64,100,0.735100,0.638838,12.740172,16.25
319,m8_ef100,8,100,32,100,0.735005,0.605883,11.345058,15.75
309,m8_ef100,8,100,16,100,0.735005,0.605883,13.591866,15.75
269,m32_ef400,32,400,32,100,0.734363,0.645286,11.679032,16.25

In [50]:
# Optional: benchmark latency murni Qdrant.
# Q02 akan dihitung dua kali karena mode negation dan no_negation memang berbeda.
latency_specs = make_latency_specs(gt_df)
latency_df = benchmark_hnsw_latency(
    latency_specs,
    collection_configs=COLLECTION_CONFIGS,
    ef_values=EF_VALUES,
    qdrant_limit_values=QDRANT_LIMIT_VALUES,
    runs=TIMING_RUNS,
)

display(latency_df)
display(
    latency_df.groupby(["collection_id", "hnsw_ef", "qdrant_limit", "search_mode"])
    .agg(
        avg_time_ms=("avg_time_ms", "mean"),
        min_time_ms=("min_time_ms", "min"),
        max_time_ms=("max_time_ms", "max"),
        std_time_ms=("std_time_ms", "mean"),
    )
    .reset_index()
    .sort_values(["collection_id", "hnsw_ef", "qdrant_limit", "search_mode"])
)

2026-05-29 01:17:27 - src.search_engine - INFO - [Init] Initializing model & database
2026-05-29 01:17:27 - httpx - INFO - HTTP Request: GET http://127.0.0.1:6333 "HTTP/1.1 200 OK"
2026-05-29 01:17:27 - sentence_transformers.SentenceTransformer - INFO - Use pytorch device_name: cuda:0
2026-05-29 01:17:27 - sentence_transformers.SentenceTransformer - INFO - Load pretrained SentenceTransformer: all-mpnet-base-v2

Benchmark latency collection m8_ef100 (rtas_hybrid_m8_ef100)

2026-05-29 01:17:28 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:28 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-05-29 01:17:28 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:28 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-05-29 01:17:28 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config_sentence_transformers.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:28 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config_sentence_transformers.json "HTTP/1.1 200 OK"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/README.md "HTTP/1.1 200 OK"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/modules.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/modules.json "HTTP/1.1 200 OK"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/sentence_bert_config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/sentence_bert_config.json "HTTP/1.1 200 OK"
2026-05-29 01:17:29 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/adapter_config.json "HTTP/1.1 404 Not Found"
2026-05-29 01:17:30 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:30 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
Loading weights: 100%|██████████| 199/199 [00:00<00:00, 271.66it/s]
MPNetModel LOAD REPORT from: sentence-transformers/all-mpnet-base-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-29 01:17:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/config.json "HTTP/1.1 200 OK"
2026-05-29 01:17:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:31 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/tokenizer_config.json "HTTP/1.1 200 OK"
2026-05-29 01:17:31 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-05-29 01:17:32 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-05-29 01:17:32 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/main/1_Pooling/config.json "HTTP/1.1 307 Temporary Redirect"
2026-05-29 01:17:32 - httpx - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/sentence-transformers/all-mpnet-base-v2/e8c3b32edf5434bc2275fc9bab85f82640a19130/1_Pooling%2Fconfig.json "HTTP/1.1 200 OK"
2026-05-29 01:17:32 - httpx - INFO - HTTP Request: GET https://huggingface.co/api/models/sentence-transformers/all-mpnet-base-v2 "HTTP/1.1 200 OK"
2026-05-29 01:17:33 - src.search_engine - INFO - [Init] Reranker: OFF (vector score only)
2026-05-29 01:17:33 - src.search_engine - INFO - [Init] Fine-tuned Parser: OFF
2026-05-29 01:17:33 - src.search_engine - INFO - [Init] LLM Query Parser: OFF
2026-05-29 01:17:33 - src.search_engine - INFO - [Init] System ready
Batches: 100%|██████████| 1/1 [00:00<00:00, 118.11it/s]
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:17:34 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef100/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m8_ef200 (rtas_hybrid_m8_ef200)

Batches: 100%|██████████| 1/1 [00:00<00:00, 82.10it/s]
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:17 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef200/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m8_ef400 (rtas_hybrid_m8_ef400)

Batches: 100%|██████████| 1/1 [00:00<00:00, 115.52it/s]
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:53 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:18:54 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m8_ef400/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m16_ef100 (rtas_hybrid_m16_ef100)

Batches: 100%|██████████| 1/1 [00:00<00:00, 96.94it/s]
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:19:31 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef100/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m16_ef200 (rtas_hybrid_m16_ef200)

Batches: 100%|██████████| 1/1 [00:00<00:00, 81.80it/s]
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:05 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:06 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef200/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m16_ef400 (rtas_hybrid_m16_ef400)

Batches: 100%|██████████| 1/1 [00:00<00:00, 105.07it/s]
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:43 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:20:44 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m16_ef400/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m32_ef100 (rtas_hybrid_m32_ef100)

Batches: 100%|██████████| 1/1 [00:00<00:00, 87.33it/s]
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:22 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:23 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef100/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m32_ef200 (rtas_hybrid_m32_ef200)

Batches: 100%|██████████| 1/1 [00:00<00:00, 121.27it/s]
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:58 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"
2026-05-29 01:21:59 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef200/points/query "HTTP/1.1 200 OK"

Benchmark latency collection m32_ef400 (rtas_hybrid_m32_ef400)

Batches: 100%|██████████| 1/1 [00:00<00:00, 116.14it/s]
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:36 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"
2026-05-29 01:22:37 - httpx - INFO - HTTP Request: POST http://127.0.0.1:6333/collections/rtas_hybrid_m32_ef400/points/query "HTTP/1.1 200 OK"

,collection_id,collection_name,m,ef_construct,eval_id,query,negation_flag,search_mode,engine_use_finetuned,engine_use_llm,final_query,hnsw_ef,qdrant_limit,runs,avg_time_ms,min_time_ms,max_time_ms,std_time_ms
0,m8_ef100,rtas_hybrid_m8_ef100,8,100,Q01,customs clearance for perishable goods,None,no_negation,False,False,customs clearance for perishable goods,16,10,25,6.740308,4.022620,47.724183,8.384921
1,m8_ef100,rtas_hybrid_m8_ef100,8,100,Q01,customs clearance for perishable goods,None,no_negation,False,False,customs clearance for perishable goods,16,20,25,6.309609,4.449370,24.033643,3.686833
2,m8_ef100,rtas_hybrid_m8_ef100,8,100,Q01,customs clearance for perishable goods,None,no_negation,False,False,customs clearance for perishable goods,16,30,25,5.461916,4.437738,6.601337,0.656137
3,m8_ef100,rtas_hybrid_m8_ef100,8,100,Q01,customs clearance for perishable goods,None,no_negation,False,False,customs clearance for perishable goods,16,40,25,5.452259,4.111198,9.036021,1.055688
4,m8_ef100,rtas_hybrid_m8_ef100,8,100,Q01,customs clearance for perishable goods,None,no_negation,False,False,customs clearance for perishable goods,16,50,25,7.085426,4.425755,15.656744,2.537229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,m32_ef400,rtas_hybrid_m32_ef400,32,400,Q03,labour standards in trade,None,no_negation,False,False,labor standards in trade,256,60,25,10.239112,7.297198,16.201939,2.425622
1796,m32_ef400,rtas_hybrid_m32_ef400,32,400,Q03,labour standards in trade,None,no_negation,False,False,labor standards in trade,256,70,25,11.151490,7.623107,19.825030,2.641349
1797,m32_ef400,rtas_hybrid_m32_ef400,32,400,Q03,labour standards in trade,None,no_negation,False,False,labor standards in trade,256,80,25,10.987043,8.027865,15.958517,2.374410
1798,m32_ef400,rtas_hybrid_m32_ef400,32,400,Q03,labour standards in trade,None,no_negation,False,False,labor standards in trade,256,90,25,9.522007,7.097239,13.915988,1.880927
1799,m32_ef400,rtas_hybrid_m32_ef400,32,400,Q03,labour standards in trade,None,no_negation,False,False,labor standards in trade,256,100,25,9.830441,7.537504,21.285303,2.976446

,collection_id,hnsw_ef,qdrant_limit,search_mode,avg_time_ms,min_time_ms,max_time_ms,std_time_ms
0,m16_ef100,16,10,negation,5.819509,3.260592,10.594630,1.709830
1,m16_ef100,16,10,no_negation,5.528431,3.606960,11.897725,1.278969
2,m16_ef100,16,20,negation,5.578455,4.154109,8.718918,1.300868
3,m16_ef100,16,20,no_negation,5.083528,3.210127,12.133643,0.887286
4,m16_ef100,16,30,negation,5.203278,3.307441,10.938694,1.352130
...,...,...,...,...,...,...,...,...
895,m8_ef400,256,80,no_negation,8.915811,5.900797,17.191057,2.242724
896,m8_ef400,256,90,negation,7.932052,6.105164,12.177887,1.445277
897,m8_ef400,256,90,no_negation,8.827939,6.037525,50.103922,3.889624
898,m8_ef400,256,100,negation,9.421354,6.092190,17.897810,2.789417
899,m8_ef400,256,100,no_negation,9.537758,6.306276,17.963043,2.451803

In [51]:
def build_final_result(
    summary_df: pd.DataFrame,
    latency_df: pd.DataFrame | None,
    k: int = K,
) -> pd.DataFrame:
    group_cols = [
        "collection_id",
        "collection_name",
        "m",
        "ef_construct",
        "hnsw_ef",
        "qdrant_limit",
    ]

    final_df = (
        summary_df.groupby(group_cols)
        .agg(
            mean_ndcg=(f"ndcg_at_{k}", "mean"),
            min_ndcg=(f"ndcg_at_{k}", "min"),
            max_ndcg=(f"ndcg_at_{k}", "max"),
            mean_eval_search_ms=("elapsed_ms_single_run", "mean"),
            mean_raw_hits=("raw_hit_count", "mean"),
            mean_unique_hits=("unique_hit_count", "mean"),
            mean_predicted_rows=("predicted_rows_before_gt_filter", "mean"),
            mean_used_rows=("predicted_rows_used", "mean"),
        )
        .reset_index()
    )

    if latency_df is not None and not latency_df.empty:
        latency_grid_df = (
            latency_df.groupby(group_cols)
            .agg(
                latency_avg_ms=("avg_time_ms", "mean"),
                latency_min_ms=("min_time_ms", "min"),
                latency_max_ms=("max_time_ms", "max"),
                latency_std_ms=("std_time_ms", "mean"),
            )
            .reset_index()
        )
        final_df = final_df.merge(latency_grid_df, on=group_cols, how="left")
    else:
        final_df["latency_avg_ms"] = np.nan
        final_df["latency_min_ms"] = np.nan
        final_df["latency_max_ms"] = np.nan
        final_df["latency_std_ms"] = np.nan

    final_df = final_df.sort_values(
        ["mean_ndcg", "latency_avg_ms", "mean_eval_search_ms", "qdrant_limit"],
        ascending=[False, True, True, True],
        na_position="last",
    ).reset_index(drop=True)
    final_df.insert(0, "overall_rank", np.arange(1, len(final_df) + 1))
    return final_df


OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
latency_result_df = latency_df if "latency_df" in globals() else pd.DataFrame()

baseline_path = OUTPUT_DIR / f"baseline_rank_qdrant_ndcg_at_{K}.csv"
summary_path = OUTPUT_DIR / f"all_collections_hnsw_summary_ndcg_at_{K}.csv"
detail_path = OUTPUT_DIR / f"all_collections_hnsw_detail_ndcg_at_{K}.csv"
latency_path = OUTPUT_DIR / "all_collections_hnsw_latency.csv"
final_grid_path = OUTPUT_DIR / f"final_result_grid_ndcg_at_{K}.csv"
final_best_overall_path = OUTPUT_DIR / f"final_result_best_overall_ndcg_at_{K}.csv"
final_best_per_collection_path = OUTPUT_DIR / f"final_result_best_per_collection_ndcg_at_{K}.csv"

baseline_df.to_csv(baseline_path, index=False)
hnsw_summary_df.to_csv(summary_path, index=False)
hnsw_detail_df.to_csv(detail_path, index=False)
latency_result_df.to_csv(latency_path, index=False)

final_result_df = build_final_result(hnsw_summary_df, latency_result_df, k=K)
final_best_overall_df = final_result_df.head(20).copy()
final_best_per_collection_df = (
    final_result_df.sort_values(["collection_id", "overall_rank"])
    .groupby("collection_id", as_index=False)
    .head(1)
    .sort_values("overall_rank")
)

final_result_df.to_csv(final_grid_path, index=False)
final_best_overall_df.to_csv(final_best_overall_path, index=False)
final_best_per_collection_df.to_csv(final_best_per_collection_path, index=False)

for collection_id, collection_summary_df in hnsw_summary_df.groupby("collection_id"):
    collection_dir = OUTPUT_DIR / collection_id
    collection_dir.mkdir(parents=True, exist_ok=True)

    baseline_df.to_csv(collection_dir / f"baseline_rank_qdrant_ndcg_at_{K}.csv", index=False)
    collection_summary_df.to_csv(collection_dir / f"hnsw_summary_ndcg_at_{K}.csv", index=False)
    hnsw_detail_df[hnsw_detail_df["collection_id"] == collection_id].to_csv(
        collection_dir / f"hnsw_detail_ndcg_at_{K}.csv", index=False
    )
    if not latency_result_df.empty and "collection_id" in latency_result_df.columns:
        collection_latency_df = latency_result_df[latency_result_df["collection_id"] == collection_id]
    else:
        collection_latency_df = latency_result_df
    collection_latency_df.to_csv(collection_dir / "hnsw_latency.csv", index=False)
    final_result_df[final_result_df["collection_id"] == collection_id].to_csv(
        collection_dir / f"final_result_grid_ndcg_at_{K}.csv", index=False
    )

print("Saved main outputs:")
print("-", baseline_path)
print("-", summary_path)
print("-", detail_path)
print("-", latency_path)
print("-", final_grid_path)
print("-", final_best_overall_path)
print("-", final_best_per_collection_path)

print("\nTop final result:")
display(final_best_overall_df)

print("\nBest per collection:")
display(final_best_per_collection_df)

Saved main outputs:
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/baseline_rank_qdrant_ndcg_at_30.csv
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/all_collections_hnsw_summary_ndcg_at_30.csv
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/all_collections_hnsw_detail_ndcg_at_30.csv
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/all_collections_hnsw_latency.csv
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/final_result_grid_ndcg_at_30.csv
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/final_result_best_overall_ndcg_at_30.csv
- /home/vinik/Github/vector-search-thesis/evaluation/hnsw_eval_results/final_result_best_per_collection_ndcg_at_30.csv

Top final result:

,overall_rank,collection_id,collection_name,m,ef_construct,hnsw_ef,qdrant_limit,mean_ndcg,min_ndcg,max_ndcg,mean_eval_search_ms,mean_raw_hits,mean_unique_hits,mean_predicted_rows,mean_used_rows,latency_avg_ms,latency_min_ms,latency_max_ms,latency_std_ms
0,1,m8_ef400,rtas_hybrid_m8_ef400,8,400,256,100,0.759278,0.702977,0.83672,12.049763,100.0,97.75,18.00,16.50,9.508657,6.092190,17.963043,2.536206
1,2,m16_ef200,rtas_hybrid_m16_ef200,16,200,128,100,0.754368,0.657336,0.83672,10.752022,100.0,97.75,18.00,16.25,7.843068,5.580487,23.748651,1.992348
2,3,m16_ef400,rtas_hybrid_m16_ef400,16,400,64,100,0.752622,0.676352,0.83672,13.113561,100.0,97.75,18.00,16.25,6.662223,5.155020,13.566785,1.378197
3,4,m16_ef400,rtas_hybrid_m16_ef400,16,400,128,100,0.751237,0.644809,0.83672,11.878017,100.0,97.75,18.00,16.25,8.167479,5.845411,15.519503,1.711919
4,5,m8_ef400,rtas_hybrid_m8_ef400,8,400,128,100,0.751129,0.670381,0.83672,11.261474,100.0,97.75,18.00,16.25,7.619170,5.376009,12.481183,1.461790
5,6,m32_ef100,rtas_hybrid_m32_ef100,32,100,256,100,0.750912,0.669514,0.83672,12.001590,100.0,97.75,18.00,16.25,9.112087,6.042045,18.678792,1.946830
6,7,m16_ef200,rtas_hybrid_m16_ef200,16,200,64,100,0.749935,0.691368,0.83672,9.965631,100.0,97.75,18.00,16.25,7.411691,4.936765,37.815896,2.576155
7,8,m32_ef200,rtas_hybrid_m32_ef200,32,200,256,100,0.748789,0.661020,0.83672,13.022440,100.0,97.75,18.00,16.00,8.884558,6.006297,19.156611,1.870925
8,9,m16_ef400,rtas_hybrid_m16_ef400,16,400,256,100,0.745883,0.676352,0.83672,12.970953,100.0,97.75,18.00,16.25,9.900054,6.610534,17.611546,2.558752
9,10,m32_ef400,rtas_hybrid_m32_ef400,32,400,64,100,0.745109,0.646302,0.83672,11.046789,100.0,97.75,18.00,16.25,7.119891,5.128961,15.424303,1.714438
10,11,m16_ef200,rtas_hybrid_m16_ef200,16,200,256,100,0.744123,0.625917,0.83672,14.427926,100.0,97.75,18.00,16.00,10.024445,6.036955,17.350791,2.740624
11,12,m8_ef400,rtas_hybrid_m8_ef400,8,400,16,100,0.742050,0.661020,0.83672,13.358433,100.0,97.75,18.00,16.00,6.565875,4.446464,14.661774,1.361739
12,13,m8_ef400,rtas_hybrid_m8_ef400,8,400,32,100,0.742050,0.661020,0.83672,13.307236,100.0,97.75,18.00,16.00,6.966066,4.253789,14.715686,1.584145
13,14,m16_ef200,rtas_hybrid_m16_ef200,16,200,16,100,0.738069,0.600919,0.83672,13.373284,100.0,97.75,18.00,16.00,6.587715,4.125034,15.357275,1.666490
14,15,m16_ef200,rtas_hybrid_m16_ef200,16,200,32,100,0.738069,0.600919,0.83672,10.160149,100.0,97.75,18.00,16.00,6.781361,4.541966,17.602268,1.795379
15,16,m16_ef400,rtas_hybrid_m16_ef400,16,400,256,90,0.737270,0.612010,0.83672,12.037596,90.0,88.00,17.25,15.75,9.268435,6.555891,18.451311,2.032814
16,17,m8_ef400,rtas_hybrid_m8_ef400,8,400,64,100,0.735100,0.638838,0.83672,12.740172,100.0,97.75,18.00,16.25,8.218934,4.500417,134.150715,8.801697
17,18,m8_ef100,rtas_hybrid_m8_ef100,8,100,32,100,0.735005,0.605883,0.83672,11.345058,100.0,97.75,18.00,15.75,6.626198,3.984146,12.729214,1.369643
18,19,m8_ef100,rtas_hybrid_m8_ef100,8,100,16,100,0.735005,0.605883,0.83672,13.591866,100.0,97.75,18.00,15.75,9.288670,4.357735,232.594629,12.343553
19,20,m32_ef400,rtas_hybrid_m32_ef400,32,400,16,100,0.734363,0.645286,0.83672,13.290422,100.0,97.75,18.00,16.25,6.246418,4.489857,15.367625,1.288171

Best per collection:

,overall_rank,collection_id,collection_name,m,ef_construct,hnsw_ef,qdrant_limit,mean_ndcg,min_ndcg,max_ndcg,mean_eval_search_ms,mean_raw_hits,mean_unique_hits,mean_predicted_rows,mean_used_rows,latency_avg_ms,latency_min_ms,latency_max_ms,latency_std_ms
0,1,m8_ef400,rtas_hybrid_m8_ef400,8,400,256,100,0.759278,0.702977,0.836720,12.049763,100.0,97.75,18.0,16.50,9.508657,6.092190,17.963043,2.536206
1,2,m16_ef200,rtas_hybrid_m16_ef200,16,200,128,100,0.754368,0.657336,0.836720,10.752022,100.0,97.75,18.0,16.25,7.843068,5.580487,23.748651,1.992348
2,3,m16_ef400,rtas_hybrid_m16_ef400,16,400,64,100,0.752622,0.676352,0.836720,13.113561,100.0,97.75,18.0,16.25,6.662223,5.155020,13.566785,1.378197
5,6,m32_ef100,rtas_hybrid_m32_ef100,32,100,256,100,0.750912,0.669514,0.836720,12.001590,100.0,97.75,18.0,16.25,9.112087,6.042045,18.678792,1.946830
7,8,m32_ef200,rtas_hybrid_m32_ef200,32,200,256,100,0.748789,0.661020,0.836720,13.022440,100.0,97.75,18.0,16.00,8.884558,6.006297,19.156611,1.870925
9,10,m32_ef400,rtas_hybrid_m32_ef400,32,400,64,100,0.745109,0.646302,0.836720,11.046789,100.0,97.75,18.0,16.25,7.119891,5.128961,15.424303,1.714438
17,18,m8_ef100,rtas_hybrid_m8_ef100,8,100,32,100,0.735005,0.605883,0.836720,11.345058,100.0,97.75,18.0,15.75,6.626198,3.984146,12.729214,1.369643
26,27,m16_ef100,rtas_hybrid_m16_ef100,16,100,16,100,0.726210,0.645286,0.810950,13.251517,100.0,97.50,18.0,16.00,6.170706,3.815937,13.945754,1.497663
63,64,m8_ef200,rtas_hybrid_m8_ef200,8,200,64,100,0.712091,0.638838,0.779092,12.565077,100.0,97.50,18.0,15.25,6.738233,4.517740,12.998014,1.294640